package provider

import (
	"context"
	"fmt"
	"strconv"

	"codeberg.org/mvdkleijn/forgejo-sdk/forgejo/v3"
	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.Resource                = &oauth2ApplicationResource{}
	_ resource.ResourceWithConfigure   = &oauth2ApplicationResource{}
	_ resource.ResourceWithImportState = &oauth2ApplicationResource{}
)

type oauth2ApplicationResource struct{ client *forgejo.Client }
type oauth2ApplicationModel struct {
	ID                 types.Int64  `tfsdk:"id"`
	Name               types.String `tfsdk:"name"`
	RedirectURIs       types.Set    `tfsdk:"redirect_uris"`
	ConfidentialClient types.Bool   `tfsdk:"confidential_client"`
	ClientID           types.String `tfsdk:"client_id"`
	ClientSecret       types.String `tfsdk:"client_secret"`
}

func NewOAuth2ApplicationResource() resource.Resource { return &oauth2ApplicationResource{} }
func (r *oauth2ApplicationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_oauth2_application"
}
func (r *oauth2ApplicationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{MarkdownDescription: "An OAuth2 application owned by the authenticated user. Authenticate as the existing application's owner when importing by numeric application ID. The client secret is returned on creation and regenerated on every update. It is stored in state; import cannot recover it. Coordinate updates with consumers. This is not an external login/authentication source.", Attributes: map[string]schema.Attribute{
		"id":                  schema.Int64Attribute{Computed: true, PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()}},
		"name":                schema.StringAttribute{Required: true, Description: "Application name."},
		"redirect_uris":       schema.SetAttribute{Required: true, ElementType: types.StringType, Description: "Allowed redirect URIs.", Validators: []validator.Set{setvalidator.SizeAtLeast(1)}},
		"confidential_client": schema.BoolAttribute{Optional: true, Computed: true, Default: booldefault.StaticBool(true), Description: "Whether this is a confidential client. Public clients require PKCE."},
		"client_id":           schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		"client_secret":       schema.StringAttribute{Computed: true, Sensitive: true, Description: "Client secret, returned on creation and regenerated by Forgejo on every update. Null after import; existing secrets are not recoverable."},
	}}
}
func (r *oauth2ApplicationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := sdkClient(req.ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider configuration", fmt.Sprintf("Expected *providerClient, got %T", req.ProviderData))
		return
	}
	r.client = c
}
func (m *oauth2ApplicationModel) from(ctx context.Context, app *forgejo.Oauth2) {
	m.ID = types.Int64Value(app.ID)
	m.Name = types.StringValue(app.Name)
	m.ConfidentialClient = types.BoolValue(app.ConfidentialClient)
	m.ClientID = types.StringValue(app.ClientID)
	values := make([]types.String, 0, len(app.RedirectURIs))
	for _, uri := range app.RedirectURIs {
		values = append(values, types.StringValue(uri))
	}
	m.RedirectURIs, _ = types.SetValueFrom(ctx, types.StringType, values)
	// Preserve the one-time secret across refresh and updates. Never replace it
	// with the empty value returned by later API reads.
	if app.ClientSecret != "" {
		m.ClientSecret = types.StringValue(app.ClientSecret)
	} else if m.ClientSecret.IsUnknown() {
		m.ClientSecret = types.StringNull()
	}
}
func (m *oauth2ApplicationModel) options(ctx context.Context) (forgejo.CreateOauth2Option, error) {
	opt := forgejo.CreateOauth2Option{Name: m.Name.ValueString(), ConfidentialClient: m.ConfidentialClient.ValueBool()}
	diags := m.RedirectURIs.ElementsAs(ctx, &opt.RedirectURIs, false)
	if diags.HasError() {
		return opt, fmt.Errorf("invalid redirect URIs")
	}
	return opt, nil
}
func (r *oauth2ApplicationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data oauth2ApplicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	opt, err := data.options(ctx)
	if err != nil {
		resp.Diagnostics.AddError("Invalid OAuth2 application", err.Error())
		return
	}
	app, _, err := r.client.CreateOauth2(opt)
	if err != nil {
		resp.Diagnostics.AddError("Unable to create OAuth2 application", "Forgejo rejected the request. Authenticate as the application owner with write:user permission.")
		return
	}
	data.from(ctx, app)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
func (r *oauth2ApplicationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data oauth2ApplicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	app, result, err := r.client.GetOauth2(data.ID.ValueInt64())
	if isNotFound(result, err) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Unable to read OAuth2 application", "Forgejo rejected the request. Verify application ownership and authentication.")
		return
	}
	data.from(ctx, app)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
func (r *oauth2ApplicationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data oauth2ApplicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	opt, err := data.options(ctx)
	if err != nil {
		resp.Diagnostics.AddError("Invalid OAuth2 application", err.Error())
		return
	}
	app, _, err := r.client.UpdateOauth2(data.ID.ValueInt64(), opt)
	if err != nil {
		resp.Diagnostics.AddError("Unable to update OAuth2 application", "Forgejo rejected the request. Verify application ownership and authentication.")
		return
	}
	data.from(ctx, app)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
func (r *oauth2ApplicationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data oauth2ApplicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := r.client.DeleteOauth2(data.ID.ValueInt64())
	if err != nil && !isNotFound(result, err) {
		resp.Diagnostics.AddError("Unable to delete OAuth2 application", "Forgejo rejected the request. Verify application ownership and authentication.")
	}
}
func (r *oauth2ApplicationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	id, err := strconv.ParseInt(req.ID, 10, 64)
	if err != nil || id <= 0 {
		resp.Diagnostics.AddError("Invalid import identifier", "Expected a positive numeric OAuth2 application ID.")
		return
	}
	app, _, err := r.client.GetOauth2(id)
	if err != nil {
		resp.Diagnostics.AddError("Unable to import OAuth2 application", "Application not found or inaccessible. Authenticate as its owner.")
		return
	}
	data := oauth2ApplicationModel{ClientSecret: types.StringNull()}
	data.from(ctx, app)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
